# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpPr1PQ8BeMDNa1vrbzsaDYvbvl0MCRo
"""

import os
def menu():
  print("Main Menu")
  print("1.create a file")
  print("2.Rename file")
  print("3.print the info in file")
  print("4.add info to the file")
  print("5.Exit")

print("Choose a aoption")
menu()
choise = int(input("Enter your option: "))
f_name = "Hello.txt"
file = open("Hello.txt","w")
file.close()
while (choise != 5):
    if(choise == 1):
      f_name =  input("Enter the file name")
      f_name = f_name+".txt"
      file = open(f_name, "w")


   elif (choise == 2):
      user_file_name = input("Enter the file name")
      user_file_name = user_file_name +".txt"
      os.rename(f_name, user_file_name )
      f_name = user_file_name
  elif (choise == 3):
    out = open(f_name, "r")
    print(out.read())
  elif (choice == 4):
     file = open(f_name, "a")
     info_toadd = input("enter the info u want to add")
     file.write(info_toadd)
     file.close()
  elif (choice == 5):
    print("thank you existing applicationn")
    break
  choice = int(inpupt("enter your option: "))